apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuardblue
  template:
    metadata:
      labels:
        app: kuardblue
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard
        ports:
        - containerPort: 8080
          name: http
